import { HEADERS } from './headers';

export const HEADER_MAPPINGS = {
    // 英語 -> 日本語
    'ISRC': HEADERS.ISRC,
    'Project Code': HEADERS.PROJECT_CODE,
    'Track Name': HEADERS.TRACK_NAME,
    'Artist Name': HEADERS.ARTIST_NAME,
    'Service': HEADERS.SERVICE_NAME,
    'Retailer': HEADERS.SERVICE_NAME,
    'Service Name': HEADERS.SERVICE_NAME,
    'Usage Month': HEADERS.USAGE_MONTH,
    'Activity Period': HEADERS.USAGE_MONTH,
    'Period': HEADERS.USAGE_MONTH,
    'Album': HEADERS.ALBUM_NAME,
    'Album Name': HEADERS.ALBUM_NAME,
    'Release Title': HEADERS.ALBUM_NAME,
    'Product Name': HEADERS.ALBUM_NAME,
    'Label': HEADERS.LABEL_NAME,
    'Label Name': HEADERS.LABEL_NAME,
    'Imprint Label': HEADERS.LABEL_NAME,
    'Publisher': HEADERS.LABEL_NAME,
    'Quantity': HEADERS.QUANTITY,
    'Unit Price': HEADERS.UNIT_PRICE,
    'Actual Price': HEADERS.DISTRIBUTION_UNIT_PRICE,  // Changed to DISTRIBUTION_UNIT_PRICE
    'Total Sales': HEADERS.TOTAL_SALES,
    'Distribution Rate': HEADERS.DISTRIBUTION_RATE,
    'Distribution Unit Price': HEADERS.DISTRIBUTION_UNIT_PRICE,
    'Master Royalty': HEADERS.MASTER_ROYALTY,
    'Copyright Unit Price': HEADERS.COPYRIGHT_UNIT_PRICE,
    'Mech. Administrative Fee': HEADERS.COPYRIGHT_UNIT_PRICE,
    'Copyright Total': HEADERS.COPYRIGHT_TOTAL,
    'Total Royalty': HEADERS.TOTAL_ROYALTY,
    'Commission': HEADERS.COMMISSION,
    'Total Payment': HEADERS.TOTAL_PAYMENT,
    'Label Share Net Receipts': HEADERS.TOTAL_PAYMENT,
    'Royalty Rate': HEADERS.ROYALTY_RATE,
    'Distribution Amount': HEADERS.DISTRIBUTION_AMOUNT,
    'Sales Type': HEADERS.SALES_TYPE,
    'Distribution Type': HEADERS.DISTRIBUTION_TYPE,
    'Trans Type': HEADERS.DISTRIBUTION_TYPE,
    'Trans Type Description': HEADERS.DISTRIBUTION_TYPE,

    // カタカナ・日本語
    'サービス': HEADERS.SERVICE_NAME,
    'サービス名': HEADERS.SERVICE_NAME,
    'アルバム': HEADERS.ALBUM_NAME,
    'アルバム名': HEADERS.ALBUM_NAME,
    '商品名': HEADERS.ALBUM_NAME,
    'レーベル': HEADERS.LABEL_NAME,
    'レーベル名': HEADERS.LABEL_NAME,
    '配信元': HEADERS.LABEL_NAME,
    '期間': HEADERS.USAGE_MONTH,
    '利用期間': HEADERS.USAGE_MONTH,
    '配信区分': HEADERS.DISTRIBUTION_TYPE,

    // その他の一般的なバリエーション
    'actual_price': HEADERS.DISTRIBUTION_UNIT_PRICE,  // Changed to DISTRIBUTION_UNIT_PRICE
    'actualPrice': HEADERS.DISTRIBUTION_UNIT_PRICE,   // Changed to DISTRIBUTION_UNIT_PRICE
    'service_name': HEADERS.SERVICE_NAME,
    'service-name': HEADERS.SERVICE_NAME,
    'serviceName': HEADERS.SERVICE_NAME,
    'retailer': HEADERS.SERVICE_NAME,
    'platform': HEADERS.SERVICE_NAME,
    'activity_period': HEADERS.USAGE_MONTH,
    'usage_month': HEADERS.USAGE_MONTH,
    'usage-month': HEADERS.USAGE_MONTH,
    'usageMonth': HEADERS.USAGE_MONTH,
    'album_name': HEADERS.ALBUM_NAME,
    'album-name': HEADERS.ALBUM_NAME,
    'albumName': HEADERS.ALBUM_NAME,
    'release_title': HEADERS.ALBUM_NAME,
    'product_name': HEADERS.ALBUM_NAME,
    'productName': HEADERS.ALBUM_NAME,
    'label_name': HEADERS.LABEL_NAME,
    'label-name': HEADERS.LABEL_NAME,
    'labelName': HEADERS.LABEL_NAME,
    'imprint_label': HEADERS.LABEL_NAME,
    'imprint-label': HEADERS.LABEL_NAME,
    'imprintLabel': HEADERS.LABEL_NAME,
    'mech_administrative_fee': HEADERS.COPYRIGHT_UNIT_PRICE,
    'mechAdministrativeFee': HEADERS.COPYRIGHT_UNIT_PRICE,
    'mech-administrative-fee': HEADERS.COPYRIGHT_UNIT_PRICE,
    'label_share_net_receipts': HEADERS.TOTAL_PAYMENT,
    'labelShareNetReceipts': HEADERS.TOTAL_PAYMENT,
    'label-share-net-receipts': HEADERS.TOTAL_PAYMENT,
    'trans_type': HEADERS.DISTRIBUTION_TYPE,
    'trans-type': HEADERS.DISTRIBUTION_TYPE,
    'transType': HEADERS.DISTRIBUTION_TYPE,
    'trans_type_description': HEADERS.DISTRIBUTION_TYPE,
    'trans-type-description': HEADERS.DISTRIBUTION_TYPE,
    'transTypeDescription': HEADERS.DISTRIBUTION_TYPE
};