export const HEADERS = {
    // Required headers
    ISRC: 'ISRC',
    PROJECT_CODE: '原盤/アルバムコード',
    TRACK_NAME: '楽曲名',
    ARTIST_NAME: 'アーティスト名',
    SERVICE_NAME: 'サービス名',
    USAGE_MONTH: '利用月',
    ALBUM_NAME: 'アルバム名',
    LABEL_NAME: 'レーベル名',
    DO: 'Do',
    AU: 'au',
    SB: 'SB',
    QUANTITY: '数量',
    UNIT_PRICE: '販売単価',
    TOTAL_SALES: '販売売上合計',
    DISTRIBUTION_RATE: '分配料率',
    DISTRIBUTION_UNIT_PRICE: '分配単価',
    MASTER_ROYALTY: '原盤使用料合計',
    COPYRIGHT_UNIT_PRICE: '著作権使用料単価',
    COPYRIGHT_TOTAL: '著作権使用料合計',
    TOTAL_ROYALTY: '使用料合計',
    COMMISSION: '手数料',
    TOTAL_PAYMENT: '総支払額',
    ROYALTY_RATE: '印税率',
    DISTRIBUTION_AMOUNT: '分配額',
    SALES_TYPE: '販売種別',
    DISTRIBUTION_TYPE: '配信区分',
    SPLIT_RATE: 'Split Rate',
    PERIOD: 'Period',
    PREFERRED_CURRENCY: 'Preferred Currency',
    TERRITORY_SUBACCOUNT: 'Territory Subaccount',
    ORCHARD_UPC: 'Orchard UPC',
    UNIT_PRICE_EN: 'Unit Price',
    DISCOUNT: 'Discount',
    MANUFACTURER_UPC: "Manufacturer's UPC",
    VOLUME: 'Volume',
    TRACK_NUMBER: 'Track #',
    TRANS_TYPE: 'Trans Type',
    RINGTONE_PUBLISHING: 'Ringtone Publishing',
    CLOUD_PUBLISHING: 'Cloud Publishing',
    PUBLISHING: 'Publishing',
    ADJUSTED_TOTAL: 'Adjusted Total',
    // Additional headers
    RELEASE_DATE: 'リリース日',
    GENRE: 'ジャンル',
    COMPOSER: '作曲者',
    LYRICIST: '作詞者',
    ARRANGER: '編曲者',
    PUBLISHER: '出版社',
    TERRITORY: '地域',
    PLATFORM: 'プラットフォーム',
    CONTENT_TYPE: 'コンテンツタイプ',
    PRICE_TIER: '価格帯',
    CURRENCY: '通貨',
    TAX: '税額',
    TAX_RATE: '税率',
    NET_AMOUNT: '純額',
    GROSS_AMOUNT: '総額',
    PAYMENT_DATE: '支払日',
    PAYMENT_STATUS: '支払状況',
    REMARKS: '備考'
};

export const HEADER_ORDER = [
    HEADERS.ISRC,
    HEADERS.PROJECT_CODE,
    HEADERS.TRACK_NAME,
    HEADERS.ARTIST_NAME,
    HEADERS.Retailer,
    HEADERS.USAGE_MONTH,
    HEADERS.ALBUM_NAME,
    HEADERS.LABEL_NAME,
    HEADERS.RELEASE_DATE,
    HEADERS.GENRE,
    HEADERS.COMPOSER,
    HEADERS.LYRICIST,
    HEADERS.ARRANGER,
    HEADERS.PUBLISHER,
    HEADERS.QUANTITY,
    HEADERS.UNIT_PRICE,
    HEADERS.TOTAL_SALES,
    HEADERS.DISTRIBUTION_RATE,
    HEADERS.DISTRIBUTION_UNIT_PRICE,
    HEADERS.MASTER_ROYALTY,
    HEADERS.COPYRIGHT_UNIT_PRICE,
    HEADERS.COPYRIGHT_TOTAL,
    HEADERS.TOTAL_ROYALTY,
    HEADERS.COMMISSION,
    HEADERS.TOTAL_PAYMENT,
    HEADERS.TAX,
    HEADERS.TAX_RATE,
    HEADERS.NET_AMOUNT,
    HEADERS.GROSS_AMOUNT,
    HEADERS.PAYMENT_DATE,
    HEADERS.PAYMENT_STATUS,
    HEADERS.DISTRIBUTION_TYPE,
    HEADERS.TERRITORY,
    HEADERS.PLATFORM,
    HEADERS.CONTENT_TYPE,
    HEADERS.PRICE_TIER,
    HEADERS.CURRENCY,
    HEADERS.REMARKS
];

export const FILE_TYPES = {
    CSV: 'csv',
    TXT: 'txt'
};